//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurtPrLyam
{
    using System;
    using System.Collections.Generic;
    
    public partial class films
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> release { get; set; }
        public Nullable<int> idCountry { get; set; }
        public Nullable<int> idDirector { get; set; }
        public Nullable<int> idGenre { get; set; }
    
        public virtual country country { get; set; }
        public virtual director director { get; set; }
        public virtual genre genre { get; set; }
    }
}
